JBEHAVE-1480 Add methods to get mandatory props from TableProperties
uarlouski/jbehave-core pull request #11
Opened 2021-04-30 16:54 UTC by uarlouski

2021-05-01 16:25 UTC, valfirst requested changes

2021-05-01 16:25 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTable.java
> +        {
please follow common formatting approach

2021-05-01 16:25 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/ExamplesTable.java
> +        private <T> T getMandatoryNonBlankProperty(String propertyName, Function<String, T> converter) {
make this method last or first

2021-05-02 07:19 UTC, valfirst approved these changes

2021-05-03 07:53 UTC, uarlouski commented
In master https://github.com/jbehave/jbehave-core/commit/6919d1683c295d48e8f01337fd593ec486ea0f38

2021-05-03 07:53 UTC, closed without merging