JBEHAVE-1493 Add converter for java.nio.file.Path
uarlouski/jbehave-core pull request #19
Opened 2021-06-08 15:02 UTC by uarlouski

2021-06-08 15:12 UTC, ikalinin1 approved these changes

2021-06-08 15:23 UTC, valfirst requested changes

2021-06-08 15:23 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/steps/ParameterConverters.java
> +                new FunctionalParameterConverter<>(String.class, Path.class, Paths::get)
please see comment above:
>// java.time.* converters

so either add an empty line between set of time-converters and new one, or move new converter higher in the collection

2021-06-08 15:26 UTC, valfirst approved these changes

2021-06-09 07:26 UTC, uarlouski commented
In master https://github.com/jbehave/jbehave-core/commit/c6550f273d68b64b0c0c9d0b1be635467aee6906

2021-06-09 07:26 UTC, closed without merging