JBEHAVE-1474 Report composed steps within its composite step
uarlouski/jbehave-core pull request #6
Opened 2021-02-10 15:37 UTC by uarlouski

2021-02-10 17:21 UTC, valfirst approved these changes

2021-02-11 05:54 UTC, valfirst requested changes
Please do not merge to master

2021-02-11 12:21 UTC, valfirst approved these changes

2021-02-11 13:51 UTC, uarlouski commented
In master https://github.com/jbehave/jbehave-core/commit/3ca6dc0d23253f70492ab4b433783d475106de41

2021-02-11 13:51 UTC, closed without merging