JBEHAVE-1475 Perform beforStep(String) hook for comment, ignorable an…
uarlouski/jbehave-core pull request #8
Opened 2021-03-10 11:12 UTC by uarlouski

…d pending steps

2021-03-11 07:22 UTC, valfirst approved these changes

2021-03-16 09:42 UTC, valfirst requested changes

2021-03-16 09:42 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/Step.java
> +    private final StepKind stepKind;
`StepType type`

2021-03-16 09:42 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/steps/StepCreator.java
> +        PARAMETERISED,
EXECUTABLE

2021-03-16 12:36 UTC, valfirst requested changes
Also please info to the docs about breaking changes

2021-03-16 12:36 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/steps/StepCreator.java
> +    {
use egyptian notation:
```
... {
...
}
```

2021-03-16 13:31 UTC, valfirst requested changes
`JBEHAVE-1475 Improve beforStep hook to be invoked for all steps` ?

2021-03-16 13:31 UTC, valfirst commented on distribution/src/site/content/migration-paths.html
> +    <li>Invoke StoryReporter#beforeStep(Step) hook before all steps (parmeterized, comment, pending, ignorable)</li>
```
... before all steps (including comment, pending, ignorable), previously the hook was invoked only for parameterized steps
```

2021-03-16 14:50 UTC, valfirst approved these changes

2021-03-16 15:18 UTC, uarlouski commented
In master https://github.com/jbehave/jbehave-core/commit/9967402c52d7d8a70539f306feca592156015f9b

2021-03-16 15:18 UTC, closed without merging